# pre-commit hooks require a user to have installed `prek`:
#   $ brew install prek
# Then install the hooks within the repo:
#   $ cd /PATH/TO/REPO
#   $ prek install
exclude: '^docs/code-comparisons/'  # skip the code comparisons directory
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        # args: [ --diff ]  # Use for previewing changes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      # ensures files are either empty or end with a blank line
      - id: end-of-file-fixer
      # sorts requirements
      - id: requirements-txt-fixer
      # valid python file
      - id: check-ast
  - repo: local
    hooks:
      - id: validate-example-notebooks
        name: validate example notebooks
        entry: python ./examples/validate_examples.py  # script is called from root directory
        language: python  # script requires the Python interpreter
        require_serial: true  # don't run in parallel because one call of the script parses all files
        additional_dependencies: [nbformat]  # Python dependency for the script
        files: ^examples/.*\.ipynb$  # this catches all .ipynb under examples/
        types: [jupyter]  # jupyter is alias for .ipynb files
